app = "app-frgtiqwl-blue-grass-9650"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  HOST = "0.0.0.0"
  APP_NAME = "DMS Backend"
  ENVIRONMENT = "production"
  BACKEND_CORS_ORIGINS = "http://localhost:5173,https://document-management-app-jbey7enb.devinapps.com"
  GOOGLE_DRIVE_ROOT_FOLDER_ID = "1LkKHLBC1yg8bNhO1lI4i404jNZtKR89V"
  GOOGLE_DRIVE_UNCATEGORIZED_FOLDER_ID = "14mnJGnzrlrykqnPUNFp8npJF8iOJfch_"
  GOOGLE_OAUTH_REDIRECT_URI = "https://app-frgtiqwl-blue-grass-9650.fly.dev/api/v1/auth/callback"
  OAUTH_DEBUG = "true"  # Enable debug logging for OAuth flow

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.routes]]
    handlers = ["*"]
    path = "/api/v1/auth/callback"

  [[http_service.routes]]
    handlers = ["*"]
    path = "/api/v1/*"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
