app = "dms-1735770776"
primary_region = "sea"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/python"]

[build.args]
  PYTHON_VERSION = "3.12"

[env]
  PORT = "8000"
  GOOGLE_CLOUD_PROJECT_ID = "hmd-445600"
  GOOGLE_DRIVE_ROOT_FOLDER = "1LkKHLBC1yg8bNhO1lI4i404jNZtKR89V"
  GOOGLE_DRIVE_UNCATEGORIZED_FOLDER_ID = "14mnJGnzrlrykqnPUNFp8npJF8iOJfch_"
  PYTHONPATH = "/app"
  GOOGLE_APPLICATION_CREDENTIALS = "/app/service-account.json"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"
